blank_issues_enabled: false

contact_links:
  - name: Xodex Engine ğŸ®
    url: https://github.com/djoezeke/xodex
    about: Modern Pygame Based Game Framework.

  - name: Xodex Documentation ğŸ“š
    url: https://djoezeke.github.io/xodexx/
    about: "If you have a question, please try the documentation first."

  - name: Xodex Discussions ğŸ’–
    url: https://github.com/djoezeke/xodex/discussions
    about: The "Discussions" forum is where you want to start.

  - name: Xodex Issues | Bug Bounty ğŸ
    url: https://github.com/djoezeke/xodex/issues
    about: Please report issues and vulnerabilities here.

  - name: Xodex Releases
    url: https://github.com/djoezeke/xodex/releases
    about: Please latest Xodex release here.
