# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Xodex CI/CD

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches: ["main", "dev"]

permissions:
  contents: read

jobs:
  build:
    name: Xodex Test, Lint, Type Check & Format.

    strategy:
      matrix:
        python-version: ["3.13"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Xodex dependencies
        run: |
          uv sync

      - name: Xodex Ruff Formatting.
        run: uv run --dev ruff format --check --diff

      - name: Xodex Ruff Type Checking.
        run: uv run --dev ruff check --fix xodex tests

      - name: Xodex Pytest Unittesting.
        run: uv run --dev pytest

      - name: Build Xodex docs
        run: |
          uv run mkdocs build

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: site/

  docs-publish:
    name: Publish Documentation to GitHub Pages.

    needs:
      - build

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Download documentation ðŸ“š artifacts
        uses: actions/download-artifact@v5
        with:
          name: documentation
          path: site/

      # - name: Configure Git Credentials
      #   run: |
      #     git config user.name github-actions[bot]
      #     git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          uv sync --force

      - name: Publish documentation ðŸ“š to GitHub Pages
        run: uv run mkdocs gh-deploy --force
        env:
          # This token is automatically provided by GitHub Actions
          # and has the necessary permissions to push to gh-pages.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
