# This workflow will upload a Python Xodex to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-Xodex-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Xodex

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  publish-build:
    name: Build Xodex Distributions & Documentation.

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Install Xodex dependencies
        run: |
          uv sync

      - name: Build distributions & Docs
        run: |
          uv build
          uv run twine check dist/*
          uv run mkdocs build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: site/

  # pypi-publish:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - publish-build
  #   permissions:
  #     # IMPORTANT: this permission is mandatory for trusted publishing
  #     id-token: write

  #   # Dedicated environments with protections for publishing are strongly recommended.
  #   # For more information, see: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/project/xodex
  #     # OPTIONAL: uncomment and update to include your PyPI project URL in the deployment status:
  #     # url: https://pypi.org/p/YOURPROJECT
  #     #
  #     # ALTERNATIVE: if your GitHub Release name is the PyPI project version string
  #     # ALTERNATIVE: exactly, uncomment the following line instead:
  #     # url: https://pypi.org/project/YOURPROJECT/${{ github.event.release.name }}

  #   steps:
  #     - name: Retrieve release distributions
  #       uses: actions/download-artifact@v5
  #       with:
  #         name: release-dists
  #         path: dist/

  #     - name: Publish release distributions ðŸ“¦ to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         Xodexs-dir: dist/

  docs-publish:
    runs-on: ubuntu-latest
    needs:
      - publish-build

    permissions:
      contents: write

    steps:
      - name: Download documentation ðŸ“š artifacts
        uses: actions/download-artifact@v5
        with:
          name: documentation
          path: site/

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync

      - name: Publish documentation ðŸ“š to GitHub Pages
        run: uv run mkdocs gh-deploy --force
        env:
          # This token is automatically provided by GitHub Actions
          # and has the necessary permissions to push to gh-pages.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
