name: Release Xodex

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      # Publish on any tag starting with a `v`, e.g., v1.0.0
      - "v*" # Push events to matching v*, i.e. v1.0.

    # branches: "release/**"

jobs:
  build:
    name: Build Xodex Distributions.

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Install Xodex dependencies
        run: |
          uv sync

      - name: Build Xodex distributions
        run: |
          uv build
          uv run twine check dist/*
          uv run mkdocs build

      - name: Upload Xodex distributions
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          if-no-files-found: error

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: site/
          if-no-files-found: error

  release:
    name: Create Xodex Release.

    needs:
      - build

    permissions:
      id-token: write
      contents: write
      attestations: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download Release Artifacts
        uses: actions/download-artifact@v6
        with:
          name: dist
          path: dist/
          merge-multiple: true

      - name: Get Release Version
        id: ver
        run: echo "VER=${GITHUB_REF_NAME#'refs/tags/'}" >> $GITHUB_OUTPUT

      - name: Generate Release Attestation
        uses: actions/attest-build-provenance@v3.0.0
        with:
          subject-path: "dist/*"

      - name: Create Tag Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          # draft: true
          name: Xodex ${{ steps.ver.outputs.VER }} release
          tag_name: ${{ github.ref_name }}
          prerelease: ${{ contains(steps.ver.outputs.VER, 'dev') }}
          # target_commitish: ${{ github.ref_name }}
          generate_release_notes: true
          files: dist/*

  docs-publish:
    name: Publish Documentation to GitHub Pages.

    needs:
      - build

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Download documentation ðŸ“š artifacts
        uses: actions/download-artifact@v5
        with:
          name: documentation
          path: site/

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          uv sync

      - name: Publish documentation ðŸ“š to GitHub Pages
        run: uv run mkdocs gh-deploy --force
        env:
          # This token is automatically provided by GitHub Actions
          # and has the necessary permissions to push to gh-pages.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
