name: Release Xodex

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      # Publish on any tag starting with a `v`, e.g., v1.0.0
      - "v*" # Push events to matching v*, i.e. v1.0.

    # branches: "release/**"

jobs:
  release-build:
    name: Build Xodex Distributions.

    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Install Xodex dependencies
        run: |
          uv sync

      - name: Build Xodex distributions
        run: |
          uv build
          uv run twine check dist/*

      - name: Upload Xodex distributions
        uses: actions/upload-artifact@v4
        id: upload-artifact
        with:
          name: dist
          path: dist/
          if-no-files-found: error

  release:
    name: Create Xodex Release.

    needs:
      - release-build

    permissions:
      id-token: write
      contents: write
      attestations: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download Release Artifacts
        uses: actions/download-artifact@v6
        with:
          artifact-ids: ${{ needs.release-build.outputs.artifact-id }}
          path: dist/
          merge-multiple: true

      - name: Get Release Version
        id: ver
        run: echo "VER=${GITHUB_REF_NAME#'refs/tags/'}" >> $GITHUB_OUTPUT

      - name: Generate Release Attestation
        uses: actions/attest-build-provenance@v3.0.0
        with:
          subject-path: "dist/*"

      - name: Create Tag Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          # draft: true
          name: Xodex ${{ steps.ver.outputs.VER }} release
          tag_name: ${{ github.ref_name }}
          prerelease: ${{ contains(steps.ver.outputs.VER, 'dev') }}
          # target_commitish: ${{ github.ref_name }}
          generate_release_notes: true
          files: dist/*
